version: '3'

volumes:
 mariadb:
  name: mariadb
  driver: local
  driver_opts:
   type: 'none' 
   o: 'bind'										 # Les Bind Mounts sont des volumes qui se montent sur un chemin d'accès à l'hôte, et ils peuvent être modifiés par d'autres processus en dehors de docker.
   device: '/home/mdarbois/data/mysql'			#Ou stocker le dossier sur votre ordinateur en local
 wordpress:
  name: wordpress
  driver: local # ici nous stockons le volume en local
  driver_opts:
   type: 'none' 									# aucun type spécifique
   o: 'bind'
   device: '/Uhome/mdarbois/data/wordpress'		#Ou stocker le dossier sur votre ordinateur en local
 
networks:
 inception:
  driver: bridge

services:
 nginx:
  image: nginx
  container_name: nginx
  volumes:
   - wordpress:/var/www/wordpress
  networks:
   - inception
  depends_on:
   - wordpress
  build:
   context: ./requirements/nginx
   dockerfile: Dockerfile
  env_file: .env
  ports:
   - "443:443"
  restart: always

 wordpress:
  image: wordpress
  container_name: wordpress
  env_file: .env
  volumes:
   - wordpress:/var/www/wordpress
  networks:
   - inception
  build: 
   context: ./requirements/wordpress
   dockerfile: Dockerfile
  depends_on:
   - mariadb
  restart: always
  expose:
   - "9000"

 mariadb:
  image: mariadb
  container_name: mariadb
  networks:
   - inception
  build:
   context: ./requirements/mariadb
   dockerfile: Dockerfile
  env_file: .env
  volumes:
   - mariadb:/var/lib/mysql
  restart: always
  expose:
   - "3306"
