---
version: "3.8"


services:
 mariadb:
  container_name: mariadb
  networks:
   - inception
  build: ./requirements/mariadb
  env_file: .env
  volumes:
   - mariadb_volume:/var/lib/mysql
  restart: always

 wordpress:
  container_name: wordpress
  env_file: .env
  volumes:
   - wordpress_volume:/var/www/html
  networks:
   - inception
  build: ./requirements/wordpress
  depends_on:
   - mariadb
  restart: always

 nginx:
  container_name: nginx
  volumes:
   - wordpress_volume:/var/www/html
  networks:
   - inception
  depends_on:
   - wordpress
  build: ./requirements/nginx
  env_file: .env
  ports:
   - 443:443
  restart: always

volumes:
 mariadb_volume:
  driver: local
  driver_opts:
   type: none
   o: bind
   device: /home/mdarbois/data/mysql
 wordpress_volume:
  driver: local
  driver_opts:
   type: none
   o: bind
   device: /home/mdarbois/data/wordpress
 
networks:
 inception:
  driver: bridge
