---
version: "3.8"

services:
 mariadb:
  container_name: mariadb
  networks:
   - inception
  build: ./requirements/mariadb
  env_file: .env
  volumes:
   - mariadb_volume:/var/lib/mysql
  restart: always

 wordpress:
  container_name: wordpress
  env_file: .env
  volumes:
   - wordpress_volume:/var/www/wordpress
  networks:
   - inception
  build: ./requirements/wordpress
  depends_on:
   - mariadb
  restart: always

 nginx:
  container_name: nginx
  volumes:
   - wordpress_volume:/var/www/wordpress
  networks:
   - inception
  depends_on:
   - wordpress
  build: ./requirements/nginx
  env_file: .env
  ports:
   - 443:443
  restart: always

 adminer:
  container_name: adminer
  networks:
   - inception
  depends_on:
   - mariadb
  build: ./requirements/bonus/adminer
  env_file: .env
  ports:
   - "8080:8080"
  restart: always

 ftp:
  container_name: ftp
  volumes:
   - wordpress_volume:/var/www/wordpress
  networks:
   - inception
  depends_on:
   - wordpress
  build: ./requirements/bonus/ftp
  env_file: .env
  ports:
    - "21:21"
  restart: always

 redis:
  container_name: redis
#  volumes:
#    - wordpress_volume:/var/www/wordpress
  networks:
    - inception
  depends_on:
    - wordpress
  build: ./requirements/bonus/redis
  env_file: .env
  ports:
    - "6379:6379"
  restart: always

volumes:
 mariadb_volume:
  driver: local
  driver_opts:
   type: none
   o: bind
   device: /home/mdarbois/data/mysql
 wordpress_volume:
  driver: local
  driver_opts:
   type: none
   o: bind
   device: /home/mdarbois/data/wordpress
 
networks:
 inception:
  driver: bridge